version: "3.9"

services:
  postgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    environment:
      - REDIS_CONNECTION_URL=redis://redis:6379

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
  
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
     - 8080:8080
     - 50000:50000
    volumes:
     - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock